version: '3'
services:

  web:
      image: prestashop/prestashop
      ports:
        - "80:80"
        - "443:443"
      environment:
        PS_DEV_MODE: 1
        PS_INSTALL_AUTO: 1
        DB_SERVER: db
        PS_LANGUAGE: fr
        PS_COUNTRY: fr
      links:
        - db
      volumes:
        - ./app:/var/www/html

  db:
    image: mysql
    restart: always
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: prestashop
    ports:
      - "8889:3306"